const produtos = [
  {
    id: 1,
    nome: "Asad Bourbon",
    preco: 330,
    categoria: "Masculino",
    imagem: "/asad.jpg",
  },
  {
    id: 2,
    nome: "Yara",
    preco: 299,
    categoria: "Feminino",
    imagem: "/yara.jpg",
  },
  {
    id: 3,
    nome: "Khamrah",
    preco: 349,
    categoria: "Unissex",
    imagem: "/khamrah.jpg",
  },
  {
    id: 4,
    nome: "Club de Nuit Intense",
    preco: 390,
    categoria: "Masculino",
    imagem: "/cdn.jpg",
  },
  {
    id: 5,
    nome: "Ameer Al Oudh",
    preco: 280,
    categoria: "Unissex",
    imagem: "/oudh.jpg",
  },
  {
    id: 6,
    nome: "Lattafa Fakhar",
    preco: 310,
    categoria: "Feminino",
    imagem: "/fakhar.jpg",
  },
  {
    id: 7,
    nome: "Oud Mood",
    preco: 270,
    categoria: "Unissex",
    imagem: "/oudmood.jpg",
  },
  {
    id: 8,
    nome: "Raghba Wood Intense",
    preco: 260,
    categoria: "Masculino",
    imagem: "/raghba.jpg",
  },
  {
    id: 9,
    nome: "Ana Abiyedh",
    preco: 250,
    categoria: "Feminino",
    imagem: "/anaabiyedh.jpg",
  },
  {
    id: 10,
    nome: "Bade’e Al Oud",
    preco: 340,
    categoria: "Unissex",
    imagem: "/badee.jpg",
  },
  {
    id: 11,
    nome: "9PM Afnan",
    preco: 360,
    categoria: "Masculino",
    imagem: "/9pm.jpg",
  },
  {
    id: 12,
    nome: "Dirham Gold",
    preco: 240,
    categoria: "Unissex",
    imagem: "/dirham.jpg",
  },
  {
    id: 13,
    nome: "Mayar",
    preco: 295,
    categoria: "Feminino",
    imagem: "/mayar.jpg",
  },
  {
    id: 14,
    nome: "Opulent Musk",
    preco: 230,
    categoria: "Unissex",
    imagem: "/musk.jpg",
  },
  {
    id: 15,
    nome: "Sheikh Al Shuyukh",
    preco: 320,
    categoria: "Masculino",
    imagem: "/sheikh.jpg",
  },
  {
    id: 16,
    nome: "Velvet Oud",
    preco: 370,
    categoria: "Unissex",
    imagem: "/velvetoud.jpg",
  },
];